// Import necessary modules
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Nav"; // Correct file path for importing Nav component
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include the Inter font */}
        <style>{inter.css}</style>
      </head>
      <body className={inter.className}>

        <NextUIProvider>
          <Nav />
          {children}
        </NextUIProvider>

      </body>
    </html>
  );
}
